services:
  lcom4:
    build:
      context: ./BackEnd/lcom4
      dockerfile: dockerfile
    container_name: lcom4_container
    ports:
      - "8001:8000"   # host:container
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      - FIREBASE_CREDS=/app/serviceAccountKey.json
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.

  lcomhs:
    build:
      context: ./BackEnd/lcomhs
      dockerfile: dockerfile
    container_name: lcomhs_container
    ports:
      - "8002:8000"   # host:container
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      - FIREBASE_CREDS=/app/serviceAccountKey.json
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.

  defectscore:
    build:
      context: ./BackEnd/defectscore
      dockerfile: dockerfile
    container_name: defect_score_container
    ports:
      - "8003:8000"   # host:container
    volumes:
      - ./serviceAccountKey.json:/app/serviceAccountKey.json:ro
    environment:
      - FIREBASE_CREDS=/app/serviceAccountKey.json
    # If you only want the gateway to call it internally, you can omit the port mapping.
    # But let's keep it to show direct access for debugging.
  
  gateway:
    build:
      context: ./BackEnd/middleware
      dockerfile: Dockerfile
    container_name: gateway_container
    ports:
      - "8080:8080"  # host:gateway
    environment:
      - LCOM4_SERVICE_URL=http://lcom4:8000
      - LCOMHS_SERVICE_URL=http://lcomhs:8000
      - DEFECT_SCORE_SERVICE_URL=http://defectscore:8000/
    depends_on:
      - lcom4
      - lcomhs
      - defectscore
  
  frontend:
    build:
      context: ./FrontEnd
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "5173:5173"  # host:frontend
    depends_on:
      - gateway