FROM python:3.12.8

WORKDIR /app

COPY common_utils /app/common_utils
COPY LCOM4 /app/LCOM4

RUN pip install --upgrade pip
RUN pip install -r LCOM4/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "LCOM4.main:app", "--host", "0.0.0.0", "--port", "8000"]